version: '3'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=my_db_user
      - POSTGRES_PASSWORD=my_db_password
      - POSTGRES_DB=my_db_name
    volumes:
      - ./db:/var/lib/postgresql/data/

  app:
    build:
      context: .
    ports:
      - '8080:8000'
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db