# Generated by Django 4.1.7 on 2023-03-22 22:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('manager', 'Управляющий'), ('worker', 'Рабочий')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/clients/%Y/%m/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Отработан'), ('conversion', 'В работе (конверсия)'), ('retention', 'В работе (ретеншн)'), ('rejected', 'Срез')], default=('conversion', 'В работе (конверсия)'), max_length=25)),
                ('project', models.CharField(choices=[('investments', 'Инвестиции'), ('cloud-solutions', 'Облачные решения'), ('drainer', 'Дрейнер'), ('exchanger', 'Обменник')], max_length=100)),
                ('contact_telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_discord', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.BigIntegerField(blank=True, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('worker_conversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion', to=settings.AUTH_USER_MODEL)),
                ('worker_retention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retention', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-registration'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('38979ba9-907a-41dc-bb5f-911095461412'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'verbose_name': 'вывод',
                'verbose_name_plural': 'Выводы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('efbeaaa9-1c92-4260-9383-61eef5c1f85e'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'verbose_name': 'депозит',
                'verbose_name_plural': 'Депозиты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('33df6537-9b68-4732-accd-70622bd9841d'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
