# Generated by Django 4.1.7 on 2023-03-17 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/clients/%Y/%m/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Отработан'), ('conversion', 'В работе (конверсия)'), ('retention', 'В работе (ретеншн)'), ('rejected', 'Срез')], default=('conversion', 'В работе (конверсия)'), max_length=25)),
                ('project', models.CharField(choices=[('investments', 'Инвестиции'), ('cloud-solutions', 'Облачные решения'), ('drainer', 'Дрейнер'), ('exchanger', 'Обменник')], max_length=100)),
                ('contact_telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_discord', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.BigIntegerField(blank=True, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-registration'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=25, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'управляющего',
                'verbose_name_plural': 'Управляющие',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.CharField(choices=[('conversion', 'Конверсия'), ('retention', 'Ретен')], max_length=25)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рабочего',
                'verbose_name_plural': 'Рабочие',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('5026102a-8abc-429a-b795-18d03f9cf794'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'verbose_name': 'вывод',
                'verbose_name_plural': 'Выводы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('3107ce9a-dd9e-4b47-ad72-db0d729e4dbf'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'verbose_name': 'депозит',
                'verbose_name_plural': 'Депозиты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('94bc2385-42f3-41c2-815f-3bd8d9736972'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='worker_conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion', to='api.worker'),
        ),
        migrations.AddField(
            model_name='client',
            name='worker_retention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retention', to='api.worker'),
        ),
    ]
