# Generated by Django 4.1.7 on 2023-03-13 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-registration'], 'verbose_name': 'клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-date'], 'verbose_name': 'депозит', 'verbose_name_plural': 'Депозиты'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'управляющего', 'verbose_name_plural': 'Управляющие'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-date'], 'verbose_name': 'вывод', 'verbose_name_plural': 'Выводы'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'рабочего', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('872f03ee-77dc-4df6-89c4-54fdf1f5e5fa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('588b5f98-f317-4cb7-b888-54ad77174829'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('34fb52c9-3247-4ccc-9ec8-6dabd3b4deb7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
