# Generated by Django 4.1.7 on 2023-03-12 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('15dcfb56-6f5f-44ea-92d5-b281243112c2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99775d7b-48fe-425a-b7ea-d50e32a85768'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('af42ef5b-78c6-48ac-b956-5b832c7dfe4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
