# Generated by Django 4.1.7 on 2023-03-23 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('540fc5ef-a442-4515-b2cb-f52c1a22bdf4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0118890a-70c6-4000-af10-eb0674bbda0f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('bot', 'Бот'), ('manager', 'Управляющий'), ('worker', 'Рабочий')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c41503c7-9e6f-4348-8cf1-e27a56d973b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
