# Generated by Django 4.1.7 on 2023-03-23 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_id_alter_comment_uid_alter_deposit_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7f4fc4f6-9178-482e-9c91-165fa86e5420'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ecb5fd26-bb49-4ebb-9f99-626815d75f2a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
