# Generated by Django 4.1.7 on 2023-03-23 00:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comment_id_alter_comment_uid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterField(
            model_name='client',
            name='project',
            field=models.CharField(blank=True, choices=[('investments', 'Инвестиции'), ('cloud-solutions', 'Облачные решения'), ('drainer', 'Дрейнер'), ('exchanger', 'Обменник')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('app', 'Приложение'), ('manager', 'Управляющий'), ('worker', 'Рабочий')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
