# Generated by Django 4.1.7 on 2023-03-13 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_uid_alter_deposit_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c1373b6d-36ec-4495-a6b9-20ddf79c3c25'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d5638e83-9fc2-4920-9576-3813af24b78e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f01fe07b-86c0-4a1a-8e14-793041ab3716'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
