# Generated by Django 4.1.7 on 2023-03-23 00:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deposit_id_withdraw_id_alter_deposit_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='id',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
