# Generated by Django 4.1.7 on 2023-03-13 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_uid_alter_deposit_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='type',
            field=models.CharField(choices=[('manager', 'Управлющий'), ('conversion', 'Конверсия')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f186e334-ad4f-4d61-90cd-95e62f6ea05b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3aa4f2e3-31e1-4592-adf7-1e28fb99c1c5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('618227cd-59ab-49a8-a2da-36c9341aa682'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
