# Generated by Django 4.1.7 on 2023-03-13 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_uid_alter_deposit_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='registration',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('aaa730dc-2fd4-4a4e-8b84-37223480ab26'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2ccda31b-4a57-418f-b7ba-9adff579b980'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('cec725f7-c980-4798-9a22-1566ec35b822'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
