# Generated by Django 4.1.7 on 2023-03-13 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_manager_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/clients/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5b4175ee-0670-4366-9768-82ef5248b665'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8652933d-e93d-4a0d-bda6-1359c7d7a928'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3ab8f441-feb3-4aa8-a240-44568dbf2f63'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
