# Generated by Django 4.1.7 on 2023-03-16 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_client_photo_alter_comment_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('62d98fd7-36c0-40b1-99a0-0f1b3b4a00b0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f2281e04-f21f-421a-91e8-d7275d441cb1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('270be37a-37d6-4de9-a869-939e64d6d1e4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
